(function(){'use strict';let catalog=[],patient=null,test=null;const e=v=>typeof escapeHtml==='function'?escapeHtml(v):String(v??'');const m=v=>typeof formatMoney==='function'?formatMoney(+v||0):'৳'+(+v||0).toFixed(2);
async function load(){if(!currentUser||!supabaseClient)return;await supabaseClient.rpc('bootstrap_lab_catalog');const r=await supabaseClient.from('lab_test_catalog').select('*').eq('active',true).order('group_name').order('test_name');if(!r.error){catalog=r.data||[];render()}}
function render(){const x=document.getElementById('labGroups');if(!x)return;const gs=[...new Set(catalog.map(a=>a.group_name))];x.innerHTML=gs.map(g=>'<div class="lab-group"><button class="lab-group-btn" onclick="labGroup(this.dataset.g)" data-g="'+e(g)+'">🧪 '+e(g)+' <span>'+catalog.filter(a=>a.group_name===g).length+'</span></button><div class="lab-test-list" data-group="'+e(g)+'">'+catalog.filter(a=>a.group_name===g).map(t=>'<button class="lab-test-btn" onclick="labTest(this.dataset.id)" data-id="'+t.id+'">'+e(t.test_name)+'<small>'+m(t.rate)+'</small></button>').join('')+'</div></div>').join('')}
window.labGroup=b=>document.querySelectorAll('.lab-test-list').forEach(x=>x.style.display=x.dataset.group===b.dataset.g?'grid':'none');
window.labTest=id=>{test=catalog.find(x=>x.id===id);if(!test)return;document.getElementById('labSelectedTest').textContent=test.test_name;document.getElementById('labResultForm').style.display='block';document.getElementById('labParameters').innerHTML=(test.parameters||[]).map(p=>'<div class="form-group"><label>'+e(p.name)+' <small>'+e(p.unit||'')+'</small></label><input class="lab-value" data-name="'+e(p.name)+'"><div class="lab-ref">'+e(p.ref||'')+'</div></div>').join('')};
window.labSearch=async()=>{const q=document.getElementById('labPatientSearch').value.trim();if(!q){document.getElementById('labPatientList').innerHTML='';return}const r=await supabaseClient.from('patients').select('id,name,age,sex,created_at').ilike('name','%'+q+'%').order('created_at',{ascending:false}).limit(15);window._lp=r.data||[];document.getElementById('labPatientList').innerHTML=window._lp.map(p=>'<button class="lab-patient" onclick="labPatient(this.dataset.id)" data-id="'+p.id+'"><b>'+e(p.name)+'</b><span>'+e(p.age||'')+' / '+e(p.sex||'')+'</span></button>').join('')};
window.labPatient=async id=>{patient=(window._lp||[]).find(p=>p.id===id);if(!patient)return;document.getElementById('labPatientSelected').textContent=patient.name+' • '+(patient.age||'')+'/'+(patient.sex||'');const r=await supabaseClient.from('lab_results').select('*').eq('patient_id',id).eq('test_id',test.id).maybeSingle();const v=r.data?.values||{};document.querySelectorAll('.lab-value').forEach(i=>i.value=v[i.dataset.name]??'');labPreview()};
async function save(status){if(!patient||!test){alert('Select patient and test first.');return}const values={};document.querySelectorAll('.lab-value').forEach(i=>values[i.dataset.name]=i.value.trim());const r=await supabaseClient.from('lab_results').upsert({user_id:currentUser.id,patient_id:patient.id,test_id:test.id,values,status,technician_name:document.getElementById('labTechnician').value.trim(),verifier_name:document.getElementById('labVerifier').value.trim(),report_no:'LAB-'+Date.now()},{onConflict:'patient_id,test_id'}).select().single();if(r.error){alert(r.error.message);return}document.getElementById('labStatus').textContent=status==='verified'?'VERIFIED':'DRAFT';labPreview()}
window.labSave=()=>save('draft');window.labVerify=()=>{if(!isAdmin()){alert('Only ADMIN can verify reports.');return}if(!document.getElementById('labVerifier').value.trim()){alert('Verifier name is required.');return}return save('verified')};
window.labPreview=()=>{if(!patient||!test)return;const v={};document.querySelectorAll('.lab-value').forEach(i=>v[i.dataset.name]=i.value.trim());document.getElementById('labPreview').innerHTML='<div class="lab-report"><div class="lab-letterhead"><h1>Satata Diagnostic Center</h1><div>Diagnostic Laboratory • Hospital Road, Chuadanga</div></div><p><b>Patient:</b> '+e(patient.name)+' &nbsp; <b>Age/Sex:</b> '+e(patient.age||'')+'/'+e(patient.sex||'')+'</p><h2>'+e(test.test_name)+'</h2><table><thead><tr><th>Parameter</th><th>Result</th><th>Unit</th><th>Reference Range</th></tr></thead><tbody>'+(test.parameters||[]).map(p=>'<tr><td>'+e(p.name)+'</td><td>'+e(v[p.name]||'')+'</td><td>'+e(p.unit||'')+'</td><td>'+e(p.ref||'')+'</td></tr>').join('')+'</tbody></table><div class="lab-sign">Technician: '+e(document.getElementById('labTechnician').value)+' &nbsp; Verified by: '+e(document.getElementById('labVerifier').value)+'</div></div>'};
window.labPrint=()=>{labPreview();setTimeout(()=>window.print(),50)};window.labInvoice=()=>{showPage('entry');document.getElementById('entryExamType').value='blood';handleEntryExamTypeChange()};window.loadLabModule=load})();